services:
  - docker

env:
  global:
    - DOCKER_IP=localhost
  matrix:
    - IMAGE=7.0-cli
    - IMAGE=7.0-fpm
    - IMAGE=nginx

before_install:
  - sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse' -y
  - sudo apt-get -qq update

install:
  - sudo apt-get install -y shellcheck

script:
  - bash test-runner.sh
